name: jsdict
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  html: ^0.15.3
  http: ^1.0.0
  ruby_text:
    git: # fork adds extra alignment options
      url: https://github.com/petlyh/RubyText
      ref: 492b148c9fddfbbc03658063efc76f51d1e851c1
  url_launcher: ^6.1.10
  get_it: ^7.3.0
  collection: ^1.17.0
  expansion_tile_card: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  provider: ^6.0.5
  expandable_text: ^2.3.0
  dynamic_color: ^1.6.5
  shared_preferences: ^2.1.2
  audioplayers: ^5.1.0
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.1

flutter_launcher_icons:
  android: true
  image_path: "icon/icon.png"
  adaptive_icon_foreground: "icon/icon-foreground.png"
  adaptive_icon_background: "#1a3332"

flutter:
  uses-material-design: true
